# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d123e50c1e6aaf5f0c2da02784d82ea077575dcb92a07ae543ff84dc622ed59c7efe2a2d9a26de89f5640868eb0e62ce8e76fa6e225c60ce5e907d2b742bdcf

test:
  secret_key_base: 1732f49bbdb35f7c567b3132f1e17bfaf1c4a6a374c30b3244bed8cd38424f926cb9db72128ce1bcd3292997b596550ec7a8b9467040c65e7fdf128df8b54808

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
